Server:
  port: 3000

Views:
  dir: 'views'
  ext: 'nunjs'

Asset:
  link: '/'

#   Configure nunjucks here.
Nunjucks:
  watch: true
  autoescape: true

#   These things are always included through the views
ViewLocals:
  livereload: true